# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditedParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider_id', models.CharField(max_length=1024, verbose_name='Service Provider ID')),
                ('trading_name', models.CharField(max_length=1024, verbose_name='Trading Name')),
                ('contact_email', models.CharField(max_length=1024, verbose_name='Contact Email')),
                ('registration_url', models.CharField(max_length=2048, verbose_name='URL (for registration page)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('dcp', 'DCP')], default='dcp', max_length=10)),
                ('accreditation_status', models.CharField(choices=[('acrdt', 'Accredited'), ('pend', 'Pending'), ('susp', 'Suspended'), ('rev', 'Revoked'), ('can', 'Cancelled')], default='pend', max_length=20)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'Accredited DCP',
                'verbose_name_plural': 'Accredited DCPs',
            },
        ),
        migrations.CreateModel(
            name='PartyAccreditationChangeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('acrdt', 'Accredited'), ('pend', 'Pending'), ('susp', 'Suspended'), ('rev', 'Revoked'), ('can', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('acrdt', 'Accredited'), ('pend', 'Pending'), ('susp', 'Suspended'), ('rev', 'Revoked'), ('can', 'Cancelled')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Moment of time when the action was performed')),
                ('actor', models.ForeignKey(blank=True, help_text='Staff member who performed the action', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditations.AccreditedParty')),
            ],
        ),
        migrations.CreateModel(
            name='PartyCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='Certificate')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('revoked', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditations.AccreditedParty')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
