# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditations', '0002_auto_20170331_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyaccreditationchangeevent',
            name='freetext_reason',
            field=models.TextField(blank=True, default='', help_text='Free text explanation why party accreditation has been changed'),
        ),
    ]
