# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accreditations', '0004_auto_20170402_0417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpartyaccess',
            unique_together=set([('party', 'user')]),
        ),
    ]
