# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditations', '0005_auto_20170402_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditedparty',
            name='dcl_host',
            field=models.CharField(default='dcl.testpoint.io', max_length=2048),
        ),
    ]
