# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accreditations', '0006_accreditedparty_dcl_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyFieldUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('new_value', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Staff member who performed the action', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='accreditedparty',
            name='dcl_host',
            field=models.CharField(default='dcl.testpoint.io', max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='accreditedparty',
            name='service_provider_id',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Service Provider ID'),
        ),
        migrations.AlterField(
            model_name='accreditedparty',
            name='trading_name',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Trading Name'),
        ),
        migrations.AddField(
            model_name='partyfieldupdate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditations.AccreditedParty'),
        ),
    ]
