# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditations', '0007_auto_20170403_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='partycertificate',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partycertificate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to='accreditations.AccreditedParty'),
        ),
    ]
