# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditations', '0008_auto_20170405_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accreditedparty',
            old_name='dcl_host',
            new_name='dcp_host',
        ),
    ]
